### ISSUE TITLE
Csf30816 Image Not LOading

### ISSUE THREAD

**Issue by RedMAngo22** [what-phone/what-phone.github.io#4]
![default](https://user-images.githubusercontent.com/28576875/31854301-8d499594-b664-11e7-8b90-b066936afb8c.png)

**Comment by GreenBayRules** [comment]
This actually is a legitimate issue I noticed this too. @Nanomotion

**Comment by RedMAngo22** [comment]
@Nanomotion

**Comment by GreenBayRules** [comment]
I'll actually fix this myself.

**Comment by GreenBayRules** [comment]
Fixed

**Comment by Nanomotion** [comment]
Thanks @RedMAngo22 for reporting a legitimate issue and @GreenBayRules for fixing it and dealing with it properly. 😉

**Comment by RedMAngo22** [comment]
Your Welcome!
