### ISSUE TITLE
Slash In Results?

### ISSUE THREAD

**Issue by redmangospros** [what-phone/what-phone.github.io#7]
![w](https://user-images.githubusercontent.com/21000033/32985711-74d0dbd6-cc8e-11e7-832f-eba0175c07aa.png)

What Is The Slash Doing There. Not using ispect elment!
@Nanomotion

**Comment by GreenBayRules** [comment]
It's obvious your using inspect element

**Comment by redmangospros** [comment]
No, I'm not!

**Comment by redmangospros** [comment]
I'm not using inspect elements. Check your self!
![l](https://user-images.githubusercontent.com/21000033/32986495-df2d4890-cca0-11e7-8819-50f18341f849.png)

**Comment by redmangospros** [comment]
#6

**Comment by GreenBayRules** [comment]
Oh wow sorry, your right :D I'll fix this.

**Comment by redmangospros** [comment]
Where Is This?

**Comment by GreenBayRules** [comment]
Fixed :D

**Comment by redmangospros** [comment]
Thanks! I Should Be a Qa!

**Comment by csf30816** [comment]
That's like that Scratch semi-colon thing :D
